---
title: "Survivor - Clean Dataframe Creation"
author: "Helen Schmidt"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    theme: cerulean
    toc: true
    toc_float: true
    code_folding: hide
    number_sections: false
---
<style>
h1, h2, h3, h4, h5, h6, legend {
    color: #046C9A;
}
</style>

***

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytext)
library(dplyr)
library(knitr)
library(readr)
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)
library(tm)
library(SnowballC)
library(XML)
library(RCurl)
library(ggpubr)
library(wesanderson)
library(reshape2)
library(MetBrewer)
library(sentimentr)
library(sna)
library(splitstackshape)
library(GGally)
library(ggraph)
library(gutenbergr)
library(igraph)
library(Matrix)
library(network)
library(tidygraph)
library(tibble)
library(formattable)
library(forcats)
library(lme4)
se <- function(x) sqrt(var(x)/length(x))  #function to calculate SE
```

```{r message=FALSE, warning=FALSE}
# define color palette
colors <- met.brewer("Hiroshige", 7, type = "discrete")
palette <- met.brewer("Hiroshige", 25, type = "continuous")

## ----- LOAD TEXT DATA ----- ##
text.data <- read.csv("survivor-text.csv")
# make sure dialogue is a character vector
text.data$Dialogue <- as.character(text.data$Dialogue)
# make speaker, recipient, and recipient type character vectors too
text.data$Speaker <- as.character(text.data$Speaker)
text.data$Recipient <- as.character(text.data$Recipient)
text.data$RecipientType <- as.character(text.data$RecipientType)
# remove space from Shii Ann's name for ease of plotting
text.data$Speaker[text.data$Speaker == "Shii Ann"] = "ShiiAnn"
text.data$Recipient[text.data$Recipient == "Shii Ann"] = "ShiiAnn"
# make sure recipient type matches recipient
text.data$RecipientType <- "Person"
text.data$RecipientType[text.data$Recipient == "Tribe"] = "Group"
text.data$RecipientType[text.data$Recipient == "Camera"] = "Camera"
# remove Probst as a speaker
text.data <- subset(text.data, text.data$Speaker != "Probst")

## ----- LOAD CHOICE DATA ----- ##
choice.data <- read.csv("dat_survivor.csv")
# capitalize first names
capFirst <- function(s) {paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")}
choice.data$Target <- capFirst(choice.data$Target)
choice.data$LeftPersonImg <- capFirst(choice.data$LeftPersonImg)
choice.data$RightPersonImg <- capFirst(choice.data$RightPersonImg)
choice.data$choice <- capFirst(choice.data$choice)
# make Shii Ann's name consistent with text.data
choice.data[choice.data == "Shiiann"] = "ShiiAnn"
# rename clips to match text.data
names(choice.data)[8] <- "ClipNumber"
```

```{r message=FALSE, warning=FALSE}
# add sentiment scores & polarity levels for each sentence
PolarityText.data <- text.data %>% 
  get_sentences() %>% #get each sentence
  sentiment() %>% #get sentiment score
  #make scores < 0 "negative" and scores > 0 "positive"
  mutate(polarity_level = ifelse(sentiment < 0, "Negative", 
                                 #else, make scores = 0 "neutral"
                                 ifelse(sentiment > 0, "Positive","Neutral"))) 

# get mean sentiment score for each speaker
AvgTargetSentiment <- PolarityText.data %>%
  group_by(Speaker) %>%
    summarize(AvgTargetSentiment = mean(sentiment))
# rename speaker to target match choice data
names(AvgTargetSentiment)[1] <- "Target"

# get mean sentiment for each choice
AvgChoiceSentiment <- AvgTargetSentiment
names(AvgChoiceSentiment)[1] <- "ChoiceOption"
names(AvgChoiceSentiment)[2] <- "AvgChoiceSentiment"

# get average target-choice pairs sentiment scores
TargetChoiceSentiment.Overall <- PolarityText.data %>%
    group_by(Speaker,Recipient) %>%
      summarize(TargetChoiceSentiment.Overall = mean(sentiment))
names(TargetChoiceSentiment.Overall)[1] <- "Target"
names(TargetChoiceSentiment.Overall)[2] <- "ChoiceOption"

# get most recent target-choice pairs sentiment scores
TargetChoiceSentiment.Recent <- PolarityText.data %>%
    group_by(Speaker,Recipient,ClipNumber) %>%
      summarize(TargetChoiceSentiment.Recent = mean(sentiment))
names(TargetChoiceSentiment.Recent)[1] <- "Target"
names(TargetChoiceSentiment.Recent)[2] <- "ChoiceOption"

# get cumulative target-choice pairs sentiment scores - average sentiment score across clips seen so far (i.e. clip 1 cumulative scores are only from clip 1, clip 2 cumulative scores are average of clip 1 and 2, etc.)
for (i in 1:length(unique(PolarityText.data$ClipNumber))) {
  # average sentiment scores across only clip 1
  if (i == 1) {
    test <- subset(PolarityText.data, PolarityText.data$ClipNumber == 1)
    clip1 <- test %>%
      group_by(Speaker,Recipient) %>%
        summarize(TargetChoiceSentiment.Cumulative = mean(sentiment))
    clip1$ClipNumber <- 1}
  # average sentiment scores across clip 1 + 2
  else if (i == 2) {
    test <- subset(PolarityText.data, c(PolarityText.data$ClipNumber == 1 | PolarityText.data$ClipNumber == 2))
    clip2 <- test %>%
      group_by(Speaker,Recipient) %>%
        summarize(TargetChoiceSentiment.Cumulative = mean(sentiment))
    clip2$ClipNumber <- 2}
  # average sentiment scores across clip 1, 2, + 3
  else if (i == 3) {
    test <- subset(PolarityText.data, c(PolarityText.data$ClipNumber == 1 | PolarityText.data$ClipNumber == 2 | PolarityText.data$ClipNumber == 3))
    clip3 <- test %>%
      group_by(Speaker,Recipient) %>%
        summarize(TargetChoiceSentiment.Cumulative = mean(sentiment))
    clip3$ClipNumber <- 3}
  # average sentiment scores across clip 1, 2, 3, + 4
  else if (i == 4) {
    test <- subset(PolarityText.data, c(PolarityText.data$ClipNumber == 1 | PolarityText.data$ClipNumber == 2 | PolarityText.data$ClipNumber == 3 | PolarityText.data$ClipNumber == 4))
    clip4 <- test %>%
      group_by(Speaker,Recipient) %>%
        summarize(TargetChoiceSentiment.Cumulative = mean(sentiment))
    clip4$ClipNumber <- 4}
  # average sentiment scores across clip 1, 2, 3, 4, + 5
  else if (i == 5) {
    test <- subset(PolarityText.data, c(PolarityText.data$ClipNumber == 1 | PolarityText.data$ClipNumber == 2 | PolarityText.data$ClipNumber == 3 | PolarityText.data$ClipNumber == 4 | PolarityText.data$ClipNumber == 5))
    clip5 <- test %>%
      group_by(Speaker,Recipient) %>%
        summarize(TargetChoiceSentiment.Cumulative = mean(sentiment))
    clip5$ClipNumber <- 5}
  # average sentiment scores across all clips
  else if (i == 6) {
    clip6 <- PolarityText.data %>%
      group_by(Speaker,Recipient) %>%
        summarize(TargetChoiceSentiment.Cumulative = mean(sentiment))
    clip6$ClipNumber <- 6}
}

# merge cumulative sentiment scores
TargetChoiceSentiment.Cumulative <- rbind(clip1,clip2,clip3,clip4,clip5,clip6)
names(TargetChoiceSentiment.Cumulative)[1] <- "Target"
names(TargetChoiceSentiment.Cumulative)[2] <- "ChoiceOption"

```

```{r message=FALSE, warning=FALSE}
# reformat choice data
unique.targets <- unique(choice.data$Target)
unique.choices <- unique(choice.data$choice)
formatted.choices <- data.frame()
# calculate % time chosen
for (x in 1:length(unique(choice.data$Target))) {
  all.choices <- data.frame()
  # subset to one target only
  test <- subset(choice.data, choice.data$Target == unique.targets[x])
  # loop through possible choices
  for (y in 1:length(unique(choice.data$choice))) {
    # how many times was each person an option?
    choices <- subset(test, c(test$LeftPersonImg == unique.choices[y] | test$RightPersonImg == unique.choices[y]))
    # group by sub ID & clip #, count the number of times someone appears as a choice vs % time chosen
    choices <- choices %>%
      group_by(PID,Target,condType,ClipNumber) %>%
        mutate(n = str_count(choice, unique.choices[y])) %>%
          summarize(option = length(Target),
                    selected = sum(n))
    # add in choice name
    choices$ChoiceOption <- unique.choices[y]
    # calculate percent of time chosen
    choices <- choices %>%
      group_by(PID,ClipNumber,condType,Target,ChoiceOption) %>%
        summarize(percent.chosen = selected/option)
    # save choices into new data frame
    all.choices <- rbind(all.choices, choices)
  }
  # save all targets into new data frame
  formatted.choices <- rbind(formatted.choices, all.choices)
}

```

```{r message=FALSE, warning=FALSE}
# merge choice data with avg. target sentiment data
df.clean <- merge(formatted.choices,AvgTargetSentiment, by="Target")

# merge with avg. choice sentiment data
df.clean <- merge(df.clean, AvgChoiceSentiment, by = "ChoiceOption")

# merge with overall target-choice sentiment data
df.clean <- merge(df.clean, TargetChoiceSentiment.Overall, by = c("Target","ChoiceOption"))

# merge with most recent target-choice sentiment data
df.clean <- merge(df.clean, TargetChoiceSentiment.Recent, by = c("Target", "ChoiceOption", "ClipNumber"))

# merge with cumulative target-choice sentiment data
df.clean <- merge(df.clean, TargetChoiceSentiment.Cumulative, by = c("Target", "ChoiceOption", "ClipNumber"))

# merge with overall choice-target sentiment data
df.clean <- merge(df.clean, TargetChoiceSentiment.Overall, by.x = c("Target","ChoiceOption"), by.y = c("ChoiceOption", "Target"), suffixes = c(".target", ".choice"))

# merge with most recent choice-target sentiment data
df.clean <- merge(df.clean, TargetChoiceSentiment.Recent, by.x = c("ClipNumber", "Target", "ChoiceOption"), by.y = c("ClipNumber", "ChoiceOption", "Target"), suffixes = c(".target", ".choice"))

# merge with cumulative choice-target sentiment data
df.clean <- merge(df.clean, TargetChoiceSentiment.Cumulative, by.x = c("ClipNumber", "Target", "ChoiceOption"), by.y = c("ClipNumber", "ChoiceOption", "Target"), suffixes = c(".target", ".choice"))

# RENAME COLUMNS
names(df.clean)[names(df.clean) == "ClipNumber"] <- "Block_Number"
names(df.clean)[names(df.clean) == "condType"] <- "Block_Type"
names(df.clean)[names(df.clean) == "ChoiceOption"] <- "Choice"
names(df.clean)[names(df.clean) == "percent.chosen"] <- "Percent_Time_Chosen"
names(df.clean)[names(df.clean) == "AvgTargetSentiment"] <- "Target_Mean_Sentiment"
names(df.clean)[names(df.clean) == "AvgChoiceSentiment"] <- "Choice_Mean_Sentiment"
names(df.clean)[names(df.clean) == "TargetChoiceSentiment.Overall.target"] <- "Target-Choice_Sentiment_Overall"
names(df.clean)[names(df.clean) == "TargetChoiceSentiment.Recent.target"] <- "Target-Choice_Sentiment_Recent"
names(df.clean)[names(df.clean) == "TargetChoiceSentiment.Cumulative.target"] <- "Target-Choice_Sentiment_Cumulative"
names(df.clean)[names(df.clean) == "TargetChoiceSentiment.Overall.choice"] <- "Choice-Target_Sentiment_Overall"
names(df.clean)[names(df.clean) == "TargetChoiceSentiment.Recent.choice"] <- "Choice-Target_Sentiment_Recent"
names(df.clean)[names(df.clean) == "TargetChoiceSentiment.Cumulative.choice"] <- "Choice-Target_Sentiment_Cumulative"

# REORDER COLUMNS
col_order <- c("PID", "Block_Type", "Block_Number","Target", "Choice", "Percent_Time_Chosen", "Target_Mean_Sentiment", "Choice_Mean_Sentiment", "Target-Choice_Sentiment_Cumulative", "Target-Choice_Sentiment_Recent", "Target-Choice_Sentiment_Overall", "Choice-Target_Sentiment_Cumulative", "Choice-Target_Sentiment_Recent", "Choice-Target_Sentiment_Overall")
df.clean <- df.clean[, col_order]
df.clean <- df.clean[order(df.clean$PID, df.clean$Block_Type),]

# save!
write.csv(df.clean,"/Volumes/GoogleDrive/My Drive/SANLab/Experiments/Survivor - Relationship Predictions with Language/Analysis/survivor_data_cleaned.csv", row.names = FALSE)
```


